#!/bin/bash
################################################################################
# VPS Security Monitor - Portable Installer
# Version: 1.0.0
# Description: Install without systemd (for containers, WSL, older systems)
################################################################################

set -e

readonly SCRIPT_VERSION="1.0.0"
readonly INSTALL_DIR="/opt/tresk"
readonly CONFIG_DIR="/etc/tresk"
readonly LOG_DIR="/var/log/tresk"

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m'

log() {
    local level="$1"
    shift
    case "$level" in
        INFO)    echo -e "${GREEN}[INFO]${NC} $*" ;;
        SUCCESS) echo -e "${GREEN}[✓]${NC} $*" ;;
        WARNING) echo -e "${YELLOW}[WARNING]${NC} $*" ;;
        ERROR)   echo -e "${RED}[ERROR]${NC} $*" ;;
        STEP)    echo -e "${CYAN}[STEP]${NC} $*" ;;
    esac
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log ERROR "This script must be run as root"
        exit 1
    fi
}

# Source the package manager module
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -f "${SCRIPT_DIR}/lib/package_manager.sh" ]]; then
    # shellcheck source=/dev/null
    source "${SCRIPT_DIR}/lib/package_manager.sh"
else
    log ERROR "package_manager.sh not found. Please use the full installer."
    exit 1
fi

create_directories() {
    log STEP "Creating directories..."
    mkdir -p "$INSTALL_DIR"/{bin,lib,config,signatures,logs}
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$LOG_DIR"
    mkdir -p "${INSTALL_DIR}/.baseline"
    mkdir -p "${INSTALL_DIR}/.alert_state"
    log SUCCESS "Directories created"
}

install_files() {
    log STEP "Installing files..."
    local source_dir
    source_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    
    # Copy main monitoring script
    if [[ -f "${source_dir}/bin/monitor.sh" ]]; then
        cp "${source_dir}/bin/monitor.sh" "${INSTALL_DIR}/bin/"
        chmod +x "${INSTALL_DIR}/bin/monitor.sh"
    else
        log ERROR "monitor.sh not found in source directory"
        exit 1
    fi
    
    # Copy Python modules
    if [[ -f "${source_dir}/lib/telegram_notifier.py" ]]; then
        cp "${source_dir}/lib/telegram_notifier.py" "${INSTALL_DIR}/lib/"
        chmod +x "${INSTALL_DIR}/lib/telegram_notifier.py"
    fi
    
    if [[ -f "${source_dir}/lib/process_analyzer.py" ]]; then
        cp "${source_dir}/lib/process_analyzer.py" "${INSTALL_DIR}/lib/"
        chmod +x "${INSTALL_DIR}/lib/process_analyzer.py"
    fi
    
    # Copy signatures
    if [[ -f "${source_dir}/signatures/threat_signatures.json" ]]; then
        cp "${source_dir}/signatures/threat_signatures.json" "${INSTALL_DIR}/signatures/"
    fi
    
    # Copy configuration
    if [[ -f "${source_dir}/config/config.conf" ]]; then
        cp "${source_dir}/config/config.conf" "${CONFIG_DIR}/config.conf"
    fi
    
    log SUCCESS "Files installed"
}

setup_cron() {
    log STEP "Setting up cron jobs..."
    
    local cron_file="/etc/cron.d/tresk"
    
    cat > "$cron_file" <<EOF
# Tresk - VPS Security Monitor Cron Jobs
# Generated by install-portable.sh

# Run monitoring every 5 minutes
*/5 * * * * root ${INSTALL_DIR}/bin/monitor.sh quick >/dev/null 2>&1

# Daily deep scan at 3:00 AM
0 3 * * * root ${INSTALL_DIR}/bin/monitor.sh deep >/dev/null 2>&1

# Daily summary at 8:00 AM
0 8 * * * root ${INSTALL_DIR}/bin/monitor.sh summary >/dev/null 2>&1

# Weekly report on Sundays at 9:00 AM
0 9 * * 0 root ${INSTALL_DIR}/bin/monitor.sh weekly >/dev/null 2>&1
EOF
    
    chmod 644 "$cron_file"
    log SUCCESS "Cron jobs configured"
}

create_symlink() {
    log STEP "Creating command symlink..."
    
    if [[ -L /usr/local/bin/tresk ]]; then
        rm -f /usr/local/bin/tresk
    fi
    ln -sf "${INSTALL_DIR}/bin/monitor.sh" /usr/local/bin/tresk
    
    log SUCCESS "Command 'tresk' is now available"
}

setup_logrotate() {
    log STEP "Setting up log rotation..."
    cat > /etc/logrotate.d/tresk <<EOF
/var/log/tresk/*.log {
    daily
    rotate 30
    compress
    delaycompress
    missingok
    notifempty
    create 0640 root root
}
EOF
    log SUCCESS "Log rotation configured"
}

configure_telegram() {
    log STEP "Configuring Telegram notifications..."
    echo
    echo "Would you like to configure Telegram now? (y/n)"
    read -r configure_now
    
    if [[ "$configure_now" =~ ^[Yy]$ ]]; then
        echo "Enter your Telegram Bot Token (from @BotFather):"
        read -r bot_token
        echo "Enter your Telegram Chat ID:"
        read -r chat_id
        
        sed -i "s/TELEGRAM_ENABLED=\"false\"/TELEGRAM_ENABLED=\"true\"/" "${CONFIG_DIR}/config.conf"
        sed -i "s/TELEGRAM_BOT_TOKEN=\"\"/TELEGRAM_BOT_TOKEN=\"${bot_token}\"/" "${CONFIG_DIR}/config.conf"
        sed -i "s/TELEGRAM_CHAT_ID=\"\"/TELEGRAM_CHAT_ID=\"${chat_id}\"/" "${CONFIG_DIR}/config.conf"
        
        log SUCCESS "Telegram configuration updated"
        
        echo "Would you like to test the Telegram connection now? (y/n)"
        read -r test_now
        if [[ "$test_now" =~ ^[Yy]$ ]]; then
            "${INSTALL_DIR}/lib/telegram_notifier.py" test || log WARNING "Telegram test failed"
        fi
    fi
}

show_summary() {
    echo
    log SUCCESS "Tresk portable installation completed!"
    echo
    echo "Installation directory: $INSTALL_DIR"
    echo "Configuration file: ${CONFIG_DIR}/config.conf"
    echo "Log directory: $LOG_DIR"
    echo
    echo "Since this is a portable installation, services are managed via cron."
    echo
    echo "Useful commands:"
    echo "  ${INSTALL_DIR}/bin/monitor.sh quick      # Run quick scan"
    echo "  ${INSTALL_DIR}/bin/monitor.sh deep       # Run deep scan"
    echo "  ${INSTALL_DIR}/bin/monitor.sh full       # Run full audit"
    echo "  tail -f ${LOG_DIR}/monitor.log           # View logs"
    echo
    echo "Quick commands:"
    echo "  tresk quick      # Run quick scan"
    echo "  tresk deep       # Run deep scan"
    echo "  tresk monitor    # Run as daemon"
    echo "  tresk --help     # Show all commands"
    echo
    echo "To uninstall: ${INSTALL_DIR}/bin/monitor.sh --uninstall"
    echo
}

main() {
    cat <<'EOF'
╔═══════════════════════════════════════════════════════════════════════════╗
║                                                                           ║
║       TRESK - VPS Security Monitor (Portable Installation) (No Systemd)           ║
║                                                                           ║
╚═══════════════════════════════════════════════════════════════════════════╝
EOF
    
    check_root
    log INFO "Starting portable installation..."
    
    # Install dependencies using modular package manager
    install_dependencies_modular || log WARNING "Some dependencies may need manual installation"
    
    create_directories
    install_files
    create_symlink
    setup_cron
    setup_logrotate
    
    if [[ "$1" != "--no-telegram" ]]; then
        configure_telegram
    fi
    
    show_summary
}

main "$@"
